# Generated by Django 5.2.5 on 2025-08-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodos', to='core.casa')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ligado', models.BooleanField(default=False)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.comodo')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligar', models.BooleanField()),
                ('ordem', models.PositiveIntegerField()),
                ('intervalo_segundos', models.PositiveIntegerField(default=0, help_text='Intervalo em segundos ANTES de executar esta ação.')),
                ('cena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.cena')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispositivo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
