# Generated by Django 5.2.5 on 2025-08-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='automacao.house'),
            preserve_default=False,
        ),
    ]
